openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 1.0.7
servers:
  - url: http://localhost:3000
    description: Optional server description, e.g. Main (production) server
paths:
  /api/users:
    get:
      summary: Returns a list of users.
      description: ユーザー一覧取得
      tags:
        - appsFoo
      operationId: getUsers
      responses:
        '200':
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
              example:
                - id: 1
                  name: "ユーザー1"
                - id: 2
                  name: "ユーザー2"
                - id: 3
                  name: "ユーザー3"
                - id: 4
                  name: "ユーザー4"
                - id: 5
                  name: "ユーザー5"
  /api/users/{id}:
    get:
      summary: Returns a list of users.
      description: 任意のユーザーを1件取得
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      tags:
        - appsFoo
      operationId: getUser
      responses:
        '200':
          description: A JSON of user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
components:
  schemas:
    User:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
        name:
          type: string

