openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 1.0.3
servers:
  - url: http://localhost:3000
    description: Optional server description, e.g. Main (production) server
paths:
  /api/users:
    get:
      summary: Returns a list of users.
      description: Optional extended description in CommonMark or HTML.
      tags:
        - appsFoo
      operationId: getUsers
      responses:
        '200':
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
  /api/users/{id}:
    get:
      summary: Returns a list of users.
      description: Optional extended description in CommonMark or HTML.
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
      tags:
        - appsFoo
      operationId: getUser
      responses:
        '200':
          description: A JSON of user
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string