openapi: 3.0.0
info:
  title: Sample API
  description: I/O Dayで使用するAPI
  version: 1.0.8
paths:
  /api/users:
    get:
      description: ユーザー一覧取得
      tags:
        - appsFoo
      operationId: getUsers
      responses:
        '200':
          description: ユーザー一覧が取得できた場合
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
              example:
                - id: 1
                  name: "ユーザー1"
                - id: 2
                  name: "ユーザー2"
                - id: 3
                  name: "ユーザー3"
                - id: 4
                  name: "ユーザー4"
                - id: 5
                  name: "ユーザー5"
components:
  schemas:
    User:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
        name:
          type: string

