
name: Auto Merge

on:
  pull_request:
    types:
      - opened
    branches:
      - main

jobs:
  release:
    name: Auto Merge
    runs-on: ubuntu-latest
    # `[automerge]` というprefixがある場合にだけこの workflow が発動する
    if: ${{ startsWith(github.event.pull_request.title, '[automerge]') }}
    steps:
      # GitHub Apps により該当PRの GitHub AutoMerge を ON にする
      - name: Generate apps token
        id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.OPENAPI_CLIENT_GENERATED_APP_ID }}
          private_key: ${{ secrets.OPENAPI_CLIENT_GENERATED_PRIVATE_KEY }}
      - name: Enable Pull Request Automerge
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ steps.generate_token.outputs.token }}
          pull-request-number: ${{ github.event.number }}

      # AutoMerge 条件（つまり branch protection）は「1人以上のApproveが必要」であるため、
      # Approve する → これにより GitHub Auto Merge が発動
      - name: Approve
        uses: hmarr/auto-approve-action@v4
        with:
          pull-request-number: ${{ github.event.number }}