# APIクライアントのバージョンを更新する
name: "OpenAPI: Update Version"

on:
  push:
    branches:
      - main
    paths:
      - "openapi.yaml"

# 複数回連続実行された場合、直列に実行されて、最後のワークフローが有効になるようにconcurrencyを設定
concurrency: ${{ github.workflow }}

jobs:
  update-openapi-version:
    runs-on: ubuntu-latest
    # selfリポジトリ に対してコミットを追加するため、対象のコミットコメントの場合、workflowは無視する
    if: ${{ !startsWith(github.event.head_commit.message, 'chore(release):') }}
    steps:
      - name: Checkout Current Repogitory
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          registry-url: https://npm.pkg.github.com

      # openapi.yamlの分析に利用
      - name: Setup yq
        uses: chrisdickinson/setup-yq@latest

      # 現在のバージョン番号を取得（例. current_version = 1.2.3）
      - name: Get vars
        id: vars
        run: |
          echo "current_version=$(yq r openapi.yaml 'info.version')" >> $GITHUB_OUTPUT

      # GitHub Apps は branch protection を bypass する設定をすることで、commit を master に直pushすることができる
      # まずは GitHub Apps のtoken を取得
      - name: Generate apps token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.OPENAPI_CLIENT_GENERATED_APP_ID }}
          private_key: ${{ secrets.OPENAPI_CLIENT_GENERATED_PRIVATE_KEY }}

      # io-openapi-clientリポジトリにPRを生成するために、io-openapi-clientリポジトリをチェックアウト
      - name: Checkout Client Repogitory
        uses: actions/checkout@v4
        with:
          token: ${{ steps.generate_token.outputs.token }}
          repository: ToruShimizu/io-openapi-client
          path: client

      # https://openapi-generator.tech/docs/usage/#generate
      - name: OpenAPI Generate typescript-fetch
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: typescript-fetch
          generator-tag: latest
          command-args: |
            -i=openapi.yaml \
            -o=client/typescript-fetch-client \
            --generate-alias-as-model \
            --enable-post-process-file

      - name: Set up GitHub Actions bot as Git user
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      # openapi.yaml で更新したバージョン番号と同じものを、package.json に対して適用する
      - name: Update release version
        run: |
          cd client/typescript-fetch-client
          npm  --no-git-tag-version version ${{ steps.vars.outputs.current_version }}


      # PR作成
      - name: Create pull request to ToruShimizu/io-openapi-client repo
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ steps.generate_token.outputs.token }}
          path: client
          delete-branch: true
          commit-message: "chore(release): npm package update version from ${{ steps.vars.outputs.current_version }} to ${{ steps.vars.outputs.current_version }}"
          # [automerge] というprefixをcommitメッセージに付与することで、次のio-openapi-clientリポジトリのworkflowでで自動マージが発火するようにしている
          title: "[automerge] chore(release): npm package update version from ${{ steps.vars.outputs.current_version }} to ${{ steps.vars.outputs.current_version }}"
          body: |
            io-openapi-typescript-fetch: ${{ steps.vars.outputs.current_version }}
          branch: chore/io-openapi-client
          # hashをbranch名に含めることで、同じPRが作られないようにする
          branch-suffix: short-commit-hash
