name: "OpenAPI: Update Version"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    # paths:
    #   - "openapi.yaml"

# 複数回連続実行された場合、直列に実行されて、最後のワークフローが有効になるようにconcurrencyを設定
concurrency: ${{ github.workflow }}

jobs:
  update-openapi-version:
    runs-on: ubuntu-latest
    # selfリポジトリ に対してコミットを追加するため、対象のコミットコメントの場合、workflowは無視する
    if: ${{ !startsWith(github.event.head_commit.message, 'chore(release):') }}
    steps:
      - name: Checkout Current Repogitory
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 16.x
          registry-url: https://npm.pkg.github.com

      # openapi.yamlの分析に利用
      - name: Setup yq
        uses: chrisdickinson/setup-yq@latest

      # 現在のバージョン番号を取得（例. current_version = 1.2.3）
      - name: Get vars
        id: vars
        run: |
          echo "::set-output name=current_version::`yq r openapi.yaml 'info.version'`"

      # 基本はpatchバージョンが更新される
      # commit comment を遡り、prefix に特定の文字列があれば minor や major バージョンを更新
      - name: Get version type
        uses: actions/github-script@v6
        id: version-type
        with:
          script: |
            const commits = ${{ toJSON(github.event.commits) }}
            for (const commit of commits.reverse()) {
              if (commit.message.startsWith('[openapi/major]')) return 'major'
              if (commit.message.startsWith('[openapi/minor]')) return 'minor'
              if (commit.message.startsWith('[openapi/patch]')) return 'patch'
            }
            return 'patch'
          result-encoding: string

      # patchバージョンを更新（例. 1.2.3 → 1.2.4）
      - name: Version Up (patch)
        if: steps.version-type.outputs.result == 'patch'
        run: |
          VERSION=${{ steps.vars.outputs.current_version }} &&
          a=( ${VERSION//./ } ) && a[2]=$((a[2] + 1))
          echo "new_version=${a[0]}.${a[1]}.${a[2]}" >> $GITHUB_ENV
      # minorバージョンを更新（例. 1.2.3 → 1.3.0）
      - name: Version Up (minor)
        if: steps.version-type.outputs.result == 'minor'
        run: |
          VERSION=${{ steps.vars.outputs.current_version }} &&
          a=( ${VERSION//./ } ) && a[1]=$((a[1] + 1))
          echo "new_version=${a[0]}.${a[1]}.0" >> $GITHUB_ENV
      # majorバージョンを更新（例. 1.2.3 → 2.0.0）
      - name: Version Up (major)
        if: steps.version-type.outputs.result == 'major'
        run: |
          VERSION=${{ steps.vars.outputs.current_version }} &&
          a=( ${VERSION//./ } ) && a[0]=$((a[0] + 1))
          echo "new_version=${a[0]}.0.0" >> $GITHUB_ENV

      # openapi.yaml のバージョンを上書きする
      - name: OpenAPI Versioning
        run: |
          sed -i -e "s/version: ${{ steps.vars.outputs.current_version }}/version: ${{ env.new_version }}/" openapi.yaml

      # GitHub Apps は branch protection を bypass する設定することで、commit を master に直pushすることができる
      # まずは GitHub Apps のtoken を取得
      - name: Generate apps token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.OPENAPI_CLIENT_GENERATED_APP_ID }}
          private_key: ${{ secrets.OPENAPI_CLIENT_GENERATED_PRIVATE_KEY }}

      # 次に backendリポジトリ へ commit
      - name: Commit New Version to ToruShimizu/io-openapi-backend repo
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore(release): openapi.yaml update version from ${{ steps.vars.outputs.current_version }} to ${{ env.new_version }}"

      # PR生成のために、io-openapi-client をチェックアウト
      - name: Checkout Client Repogitory
        uses: actions/checkout@v4
        with:
          token: ${{ steps.generate_token.outputs.token }}
          repository: ToruShimizu/io-openapi-client
          path: client

      # https://openapi-generator.tech/docs/usage/#generate
      - name: OpenAPI Generate typescript-fetch
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: typescript-fetch
          generator-tag: latest
          command-args: |
            -i=openapi.yaml \
            -o=client/typescript-fetch-client \
            --generate-alias-as-model \
            --enable-post-process-file

      - name: Set up GitHub Actions bot as Git user
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      # openapi.yaml で更新したバージョン番号と同じものを、package.json に対して適用する
      - name: Update release version
        run: |
          cd client/typescript-fetch-client
          npm version ${{ env.new_version }}

      # PR作成
      # [automerge] というprefixをcommit commentにつけることで、次のstepで自動マージが発火する
      - name: Create pull request to ToruShimizu/io-openapi-client repo
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ steps.generate_token.outputs.token }}
          path: client
          delete-branch: true
          commit-message: "chore(release): npm package update version from ${{ steps.vars.outputs.current_version }} to ${{ env.new_version }}"
          title: "[automerge] chore(release): npm package update version from ${{ steps.vars.outputs.current_version }} to ${{ env.new_version }}"
          body: |
            io-openapi-typescript-fetch: ${{ env.new_version }}
          branch: chore/io-openapi-client
          branch-suffix: short-commit-hash # 同じプルリクは作らない
